var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            //'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_Paavo_2024_1 = new ol.format.GeoJSON();
var features_Paavo_2024_1 = format_Paavo_2024_1.readFeatures(json_Paavo_2024_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Paavo_2024_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Paavo_2024_1.addFeatures(features_Paavo_2024_1);
var lyr_Paavo_2024_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Paavo_2024_1, 
                style: style_Paavo_2024_1,
                popuplayertitle: "Paavo_2024",
                interactive: true,
    title: 'Paavo_2024<br />\
    <img src="styles/legend/Paavo_2024_1_0.png" /> 0 - 1<br />\
    <img src="styles/legend/Paavo_2024_1_1.png" /> 1 - 4<br />\
    <img src="styles/legend/Paavo_2024_1_2.png" /> 4 - 6<br />\
    <img src="styles/legend/Paavo_2024_1_3.png" /> 6 - 10<br />\
    <img src="styles/legend/Paavo_2024_1_4.png" /> 10 - 16<br />\
    <img src="styles/legend/Paavo_2024_1_5.png" /> 16 - 26<br />\
    <img src="styles/legend/Paavo_2024_1_6.png" /> 26 - 57<br />\
    <img src="styles/legend/Paavo_2024_1_7.png" /> 57 - 252<br />\
    <img src="styles/legend/Paavo_2024_1_8.png" /> 252 - 1719<br />\
    <img src="styles/legend/Paavo_2024_1_9.png" /> 1719 - 84646<br />'
        });

lyr_OpenStreetMap_0.setVisible(true);lyr_Paavo_2024_1.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_Paavo_2024_1];
lyr_Paavo_2024_1.set('fieldAliases', {'fid': 'fid', 'postinumer': 'postinumer', 'nimi': 'nimi', 'namn': 'namn', 'euref_x': 'euref_x', 'euref_y': 'euref_y', 'pinta_ala': 'pinta_ala', 'vuosi': 'vuosi', 'kunta': 'kunta', 'he_vakiy': 'he_vakiy', 'he_naiset': 'he_naiset', 'he_miehet': 'he_miehet', 'he_kika': 'he_kika', 'he_0_2': 'he_0_2', 'he_3_6': 'he_3_6', 'he_7_12': 'he_7_12', 'he_13_15': 'he_13_15', 'he_16_17': 'he_16_17', 'he_18_19': 'he_18_19', 'he_20_24': 'he_20_24', 'he_25_29': 'he_25_29', 'he_30_34': 'he_30_34', 'he_35_39': 'he_35_39', 'he_40_44': 'he_40_44', 'he_45_49': 'he_45_49', 'he_50_54': 'he_50_54', 'he_55_59': 'he_55_59', 'he_60_64': 'he_60_64', 'he_65_69': 'he_65_69', 'he_70_74': 'he_70_74', 'he_75_79': 'he_75_79', 'he_80_84': 'he_80_84', 'he_85_': 'he_85_', 'ko_ika18y': 'ko_ika18y', 'ko_perus': 'ko_perus', 'ko_koul': 'ko_koul', 'ko_yliop': 'ko_yliop', 'ko_ammat': 'ko_ammat', 'ko_al_kork': 'ko_al_kork', 'ko_yl_kork': 'ko_yl_kork', 'hr_tuy': 'hr_tuy', 'hr_ktu': 'hr_ktu', 'hr_mtu': 'hr_mtu', 'hr_pi_tul': 'hr_pi_tul', 'hr_ke_tul': 'hr_ke_tul', 'hr_hy_tul': 'hr_hy_tul', 'hr_ovy': 'hr_ovy', 'te_taly': 'te_taly', 'te_takk': 'te_takk', 'te_as_valj': 'te_as_valj', 'te_yks': 'te_yks', 'te_nuor': 'te_nuor', 'te_eil_np': 'te_eil_np', 'te_laps': 'te_laps', 'te_plap': 'te_plap', 'te_aklap': 'te_aklap', 'te_klap': 'te_klap', 'te_teini': 'te_teini', 'te_yhlap': 'te_yhlap', 'te_aik': 'te_aik', 'te_elak': 'te_elak', 'te_omis_as': 'te_omis_as', 'te_vuok_as': 'te_vuok_as', 'te_muu_as': 'te_muu_as', 'tr_kuty': 'tr_kuty', 'tr_ktu': 'tr_ktu', 'tr_mtu': 'tr_mtu', 'tr_pi_tul': 'tr_pi_tul', 'tr_ke_tul': 'tr_ke_tul', 'tr_hy_tul': 'tr_hy_tul', 'tr_ovy': 'tr_ovy', 'ra_ke': 'ra_ke', 'ra_raky': 'ra_raky', 'ra_muut': 'ra_muut', 'ra_asrak': 'ra_asrak', 'ra_asunn': 'ra_asunn', 'ra_as_kpa': 'ra_as_kpa', 'ra_pt_as': 'ra_pt_as', 'ra_kt_as': 'ra_kt_as', 'ra_muu_as': 'ra_muu_as', 'tp_tyopy': 'tp_tyopy', 'tp_alku_a': 'tp_alku_a', 'tp_jalo_bf': 'tp_jalo_bf', 'tp_palv_gu': 'tp_palv_gu', 'tp_a_maat': 'tp_a_maat', 'tp_b_kaiv': 'tp_b_kaiv', 'tp_c_teol': 'tp_c_teol', 'tp_d_ener': 'tp_d_ener', 'tp_e_vesi': 'tp_e_vesi', 'tp_f_rake': 'tp_f_rake', 'tp_g_kaup': 'tp_g_kaup', 'tp_h_kulj': 'tp_h_kulj', 'tp_i_majo': 'tp_i_majo', 'tp_j_info': 'tp_j_info', 'tp_k_raho': 'tp_k_raho', 'tp_l_kiin': 'tp_l_kiin', 'tp_m_erik': 'tp_m_erik', 'tp_n_hall': 'tp_n_hall', 'tp_o_julk': 'tp_o_julk', 'tp_p_koul': 'tp_p_koul', 'tp_q_terv': 'tp_q_terv', 'tp_r_taid': 'tp_r_taid', 'tp_s_muup': 'tp_s_muup', 'tp_t_koti': 'tp_t_koti', 'tp_u_kans': 'tp_u_kans', 'tp_x_tunt': 'tp_x_tunt', 'pt_vakiy': 'pt_vakiy', 'pt_tyoll': 'pt_tyoll', 'pt_tyott': 'pt_tyott', 'pt_0_14': 'pt_0_14', 'pt_opisk': 'pt_opisk', 'pt_elakel': 'pt_elakel', 'pt_muut': 'pt_muut', 'tulot_per': 'tulot_per', });
lyr_Paavo_2024_1.set('fieldImages', {'fid': 'TextEdit', 'postinumer': 'TextEdit', 'nimi': 'TextEdit', 'namn': 'TextEdit', 'euref_x': 'TextEdit', 'euref_y': 'TextEdit', 'pinta_ala': 'TextEdit', 'vuosi': 'TextEdit', 'kunta': 'TextEdit', 'he_vakiy': 'TextEdit', 'he_naiset': 'TextEdit', 'he_miehet': 'TextEdit', 'he_kika': 'TextEdit', 'he_0_2': 'TextEdit', 'he_3_6': 'TextEdit', 'he_7_12': 'TextEdit', 'he_13_15': 'TextEdit', 'he_16_17': 'TextEdit', 'he_18_19': 'TextEdit', 'he_20_24': 'TextEdit', 'he_25_29': 'TextEdit', 'he_30_34': 'TextEdit', 'he_35_39': 'TextEdit', 'he_40_44': 'TextEdit', 'he_45_49': 'TextEdit', 'he_50_54': 'TextEdit', 'he_55_59': 'TextEdit', 'he_60_64': 'TextEdit', 'he_65_69': 'TextEdit', 'he_70_74': 'TextEdit', 'he_75_79': 'TextEdit', 'he_80_84': 'TextEdit', 'he_85_': 'TextEdit', 'ko_ika18y': 'TextEdit', 'ko_perus': 'TextEdit', 'ko_koul': 'TextEdit', 'ko_yliop': 'TextEdit', 'ko_ammat': 'TextEdit', 'ko_al_kork': 'TextEdit', 'ko_yl_kork': 'TextEdit', 'hr_tuy': 'TextEdit', 'hr_ktu': 'TextEdit', 'hr_mtu': 'TextEdit', 'hr_pi_tul': 'TextEdit', 'hr_ke_tul': 'TextEdit', 'hr_hy_tul': 'TextEdit', 'hr_ovy': 'TextEdit', 'te_taly': 'TextEdit', 'te_takk': 'TextEdit', 'te_as_valj': 'TextEdit', 'te_yks': 'TextEdit', 'te_nuor': 'TextEdit', 'te_eil_np': 'TextEdit', 'te_laps': 'TextEdit', 'te_plap': 'TextEdit', 'te_aklap': 'TextEdit', 'te_klap': 'TextEdit', 'te_teini': 'TextEdit', 'te_yhlap': 'TextEdit', 'te_aik': 'TextEdit', 'te_elak': 'TextEdit', 'te_omis_as': 'TextEdit', 'te_vuok_as': 'TextEdit', 'te_muu_as': 'TextEdit', 'tr_kuty': 'TextEdit', 'tr_ktu': 'TextEdit', 'tr_mtu': 'TextEdit', 'tr_pi_tul': 'TextEdit', 'tr_ke_tul': 'TextEdit', 'tr_hy_tul': 'TextEdit', 'tr_ovy': 'TextEdit', 'ra_ke': 'TextEdit', 'ra_raky': 'TextEdit', 'ra_muut': 'TextEdit', 'ra_asrak': 'TextEdit', 'ra_asunn': 'TextEdit', 'ra_as_kpa': 'TextEdit', 'ra_pt_as': 'TextEdit', 'ra_kt_as': 'TextEdit', 'ra_muu_as': 'TextEdit', 'tp_tyopy': 'TextEdit', 'tp_alku_a': 'TextEdit', 'tp_jalo_bf': 'TextEdit', 'tp_palv_gu': 'TextEdit', 'tp_a_maat': 'TextEdit', 'tp_b_kaiv': 'TextEdit', 'tp_c_teol': 'TextEdit', 'tp_d_ener': 'TextEdit', 'tp_e_vesi': 'TextEdit', 'tp_f_rake': 'TextEdit', 'tp_g_kaup': 'TextEdit', 'tp_h_kulj': 'TextEdit', 'tp_i_majo': 'TextEdit', 'tp_j_info': 'TextEdit', 'tp_k_raho': 'TextEdit', 'tp_l_kiin': 'TextEdit', 'tp_m_erik': 'TextEdit', 'tp_n_hall': 'TextEdit', 'tp_o_julk': 'TextEdit', 'tp_p_koul': 'TextEdit', 'tp_q_terv': 'TextEdit', 'tp_r_taid': 'TextEdit', 'tp_s_muup': 'TextEdit', 'tp_t_koti': 'TextEdit', 'tp_u_kans': 'TextEdit', 'tp_x_tunt': 'TextEdit', 'pt_vakiy': 'TextEdit', 'pt_tyoll': 'TextEdit', 'pt_tyott': 'TextEdit', 'pt_0_14': 'TextEdit', 'pt_opisk': 'TextEdit', 'pt_elakel': 'TextEdit', 'pt_muut': 'TextEdit', 'tulot_per': 'Range', });
lyr_Paavo_2024_1.set('fieldLabels', {'fid': 'no label', 'postinumer': 'no label', 'nimi': 'no label', 'namn': 'no label', 'euref_x': 'no label', 'euref_y': 'no label', 'pinta_ala': 'no label', 'vuosi': 'no label', 'kunta': 'no label', 'he_vakiy': 'no label', 'he_naiset': 'no label', 'he_miehet': 'no label', 'he_kika': 'no label', 'he_0_2': 'no label', 'he_3_6': 'no label', 'he_7_12': 'no label', 'he_13_15': 'no label', 'he_16_17': 'no label', 'he_18_19': 'no label', 'he_20_24': 'no label', 'he_25_29': 'no label', 'he_30_34': 'no label', 'he_35_39': 'no label', 'he_40_44': 'no label', 'he_45_49': 'no label', 'he_50_54': 'no label', 'he_55_59': 'no label', 'he_60_64': 'no label', 'he_65_69': 'no label', 'he_70_74': 'no label', 'he_75_79': 'no label', 'he_80_84': 'no label', 'he_85_': 'no label', 'ko_ika18y': 'no label', 'ko_perus': 'no label', 'ko_koul': 'no label', 'ko_yliop': 'no label', 'ko_ammat': 'no label', 'ko_al_kork': 'no label', 'ko_yl_kork': 'no label', 'hr_tuy': 'no label', 'hr_ktu': 'no label', 'hr_mtu': 'no label', 'hr_pi_tul': 'no label', 'hr_ke_tul': 'no label', 'hr_hy_tul': 'no label', 'hr_ovy': 'no label', 'te_taly': 'no label', 'te_takk': 'no label', 'te_as_valj': 'no label', 'te_yks': 'no label', 'te_nuor': 'no label', 'te_eil_np': 'no label', 'te_laps': 'no label', 'te_plap': 'no label', 'te_aklap': 'no label', 'te_klap': 'no label', 'te_teini': 'no label', 'te_yhlap': 'no label', 'te_aik': 'no label', 'te_elak': 'no label', 'te_omis_as': 'no label', 'te_vuok_as': 'no label', 'te_muu_as': 'no label', 'tr_kuty': 'no label', 'tr_ktu': 'no label', 'tr_mtu': 'no label', 'tr_pi_tul': 'no label', 'tr_ke_tul': 'no label', 'tr_hy_tul': 'no label', 'tr_ovy': 'no label', 'ra_ke': 'no label', 'ra_raky': 'no label', 'ra_muut': 'no label', 'ra_asrak': 'no label', 'ra_asunn': 'no label', 'ra_as_kpa': 'no label', 'ra_pt_as': 'no label', 'ra_kt_as': 'no label', 'ra_muu_as': 'no label', 'tp_tyopy': 'no label', 'tp_alku_a': 'no label', 'tp_jalo_bf': 'no label', 'tp_palv_gu': 'no label', 'tp_a_maat': 'no label', 'tp_b_kaiv': 'no label', 'tp_c_teol': 'no label', 'tp_d_ener': 'no label', 'tp_e_vesi': 'no label', 'tp_f_rake': 'no label', 'tp_g_kaup': 'no label', 'tp_h_kulj': 'no label', 'tp_i_majo': 'no label', 'tp_j_info': 'no label', 'tp_k_raho': 'no label', 'tp_l_kiin': 'no label', 'tp_m_erik': 'no label', 'tp_n_hall': 'no label', 'tp_o_julk': 'no label', 'tp_p_koul': 'no label', 'tp_q_terv': 'no label', 'tp_r_taid': 'no label', 'tp_s_muup': 'no label', 'tp_t_koti': 'no label', 'tp_u_kans': 'no label', 'tp_x_tunt': 'no label', 'pt_vakiy': 'no label', 'pt_tyoll': 'no label', 'pt_tyott': 'no label', 'pt_0_14': 'no label', 'pt_opisk': 'no label', 'pt_elakel': 'no label', 'pt_muut': 'no label', 'tulot_per': 'no label', });
lyr_Paavo_2024_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});